from pathlib import Path

CWD: Path = Path(__file__).parent
DATA_DIR: Path = CWD.parent / "data"

MAIN_EDITION_CLASSIFIER_MODEL_MD5: str = "0b93fa05a36164033fffccba4a1c34ce"
MAIN_EDITION_CLASSIFIER_MODEL_FILE_NAME: str = (
    f"main_edition.ftz.{MAIN_EDITION_CLASSIFIER_MODEL_MD5}"
)
MAIN_EDITION_CLASSIFIER_MODEL_PATH: str = str(
    DATA_DIR / MAIN_EDITION_CLASSIFIER_MODEL_FILE_NAME
)

MODULE_CLASSIFIER_MODEL_MD5: str = "27d0533c0cc3e76058d0041d7ea6d9f1"
MODULE_CLASSIFIER_MODEL_FILE: str = (
    f"classifier.model.ftz.{MODULE_CLASSIFIER_MODEL_MD5}"
)
MODULE_CLASSIFIER_DEFAULT_MODEL_PATH: str = str(DATA_DIR / MODULE_CLASSIFIER_MODEL_FILE)


AWS_S3_MODELS_BUCKET: str = "ts-shared-models"
