#!/usr/bin/env python

import argparse
from typing import List

import sys
from module_classifier.settings import CLASS_FIELD, TEXT_FIELDS
from module_trainer.training import Trainer

ENCODING = "UTF-8"

if __name__ == "__main__":
    parser = argparse.ArgumentParser("Train a new module classifier model.")
    parser.add_argument(
        "--input",
        "-i",
        # type=argparse.FileType(encoding=ENCODING),
        type=str,
        metavar="FILE",
        # default=sys.stdin,
        required=True,
        help="The input file (CSV). If not given, reads from stdin.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        metavar="FILE",
        required=True,
        help="The output file (classifier model in binary format).",
    )
    parser.add_argument(
        "--text-fields",
        type=List[str],
        nargs="+",
        metavar="COLUMN",
        default=TEXT_FIELDS,
        help=f"The column(s) containing the text fields in the input file. Defaults to '{' '.join(TEXT_FIELDS)}'.",
    )
    parser.add_argument(
        "--class-field",
        type=str,
        default=CLASS_FIELD,
        metavar="COLUMN",
        help=f"The column containing the class in the input file. Defaults to '{CLASS_FIELD}'.",
    )

    args = parser.parse_args()

    trainer = Trainer()
    trainer.train_model(args.input, args.output, text_fields=args.text_fields)
